# Generated by Django 5.2.5 on 2025-08-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='children',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_children',
        ),
    ]
